### ISSUE TITLE
[Request deployment] New Hub: {{ HUB NAME }}

### ISSUE THREAD

**Issue by GeorgianaElena** [GeorgianaElena/pilot-hubs#8]
### The GitHub handle of the community representative

kdjdnf

### Hub important dates

dsjcubhdfvuhdf

### Hub Authentication Type

GitHub (e.g., @mygithubhandle)

### First Hub Administrators

hijdhbdfv

### [GitHub Auth only] How would you like to manage your users?

Manually, by adding specific GitHub handles in the JupyterHub Admin panel

### [GitHub Teams Auth only] Profile restriction based on team membership

cshjdfvbhdf

### Hub logo image URL

dfdffgd

### Hub logo website URL

dfdfdf

### Hub user image GitHub repository

uyghuyfgyt

### Hub user image tag and name

uiguyfytf

### Extra features you would like to enable

- [X] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### (Optional) Preferred cloud provider

No preference

### (Optional) Billing and Cloud account

I have read the docs and have setup the billing and cloud accounts

### Other relevant information to the features above

iuygyitf

### Tasks to deploy the hub

- [ ] 1. Deploy information filled in above
- [ ] 2. Engineer who will deploy the hub is assigned
- [ ] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [ ] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state
